### PR TITLE
Add library path + fix link

### PR DESCRIPTION
**Pull request by Sigri44**
Add library path + fix link

### CODE REVIEW

**Comment by jfroment** [comment]
Hello, thanks for the contribution!

But what is the library folder ? ``HOST_LIBRARY_PATH`` is unknown to me.

**Comment by Sigri44** [comment]
> Hello, thanks for the contribution!
> 
> But what is the library folder ? `HOST_LIBRARY_PATH` is unknown to me.

How you're right, have added that because without, plex/sonarr/radarr can't communicate. There is no common folder

**Comment by tblaudez** [comment]
> > Hello, thanks for the contribution!
> > But what is the library folder ? `HOST_LIBRARY_PATH` is unknown to me.
> 
> How you're right, have added that because without, plex/sonarr/radarr can't communicate. There is no common folder

Isn't the common folder for sonarr/radarr/plex supposed to be stored in the `HOST_MEDIA_PATH` variable ?
I personnally set this variable to `/data/media` (_preferred method of the *arr team_) so that my containers can all access my media files.

**Comment by Sigri44** [comment]
> Isn't the common folder for sonarr/radarr/plex supposed to be stored in the `HOST_MEDIA_PATH` variable ?
> I personnally set this variable to `/data/media` (_preferred method of the *arr team_) so that my containers can all access my media files.

Hum hum but library is /data/library and your : HOST_MEDIA_PATH="/data/torrents"
So your lib/media is into torrents folder !?

/data directory
image

**Comment by tblaudez** [comment]
> Hum hum but library is /data/library and your : HOST_MEDIA_PATH="/data/torrents" So your lib/media is into torrents folder !?

To my understanding, the default configuration of this repository is to have all media files in the `/data/torrents` folder (_HOST_MEDIA_PATH_) and then having a subfolder for downloaded files (_DOWNLOAD_SUBFOLDER_) which will then be set (by default) to `/data/torrents/deluge`

I personnaly think this default naming scheme is not ideal which is why I edited it to my liking : my _HOST_MEDIA_PATH_ variable is set to `/data/media` and my _DOWNLOAD_SUBFOLDER_ variable is set to `downloads`.
This way my sonarr/radarr/plex containers can all access **both** my media folder and my download folder for file management.

image

---

By the way @jfroment, I think there may be a typo in [this line](https://github.com/jfroment/seedbox/blob/f42022744bac36da3a9bd27cc934b959270329f0/.env.sample#L24) of the sample env file, the download subfolder will be located in HOST_MEDIA_PATH and not in HOST_CONFIG_PATH (as seen [here](https://github.com/jfroment/seedbox/blob/f42022744bac36da3a9bd27cc934b959270329f0/docker-compose.sample.yaml#L23))

**Comment by Sigri44** [comment]
> > Hum hum but library is /data/library and your : HOST_MEDIA_PATH="/data/torrents" So your lib/media is into torrents folder !?
> 
> To my understanding, the default configuration of this repository is to have all media files in the `/data/torrents` folder (_HOST_MEDIA_PATH_) and then having a subfolder for downloaded files (_DOWNLOAD_SUBFOLDER_) which will then be set (by default) to `/data/torrents/deluge`
> 
> I personnaly think this default naming scheme is not ideal which is way I edited it to my liking : my _HOST_MEDIA_PATH_ variable is set to `/data/media` and my _DOWNLOAD_SUBFOLDER_ variable is set to `downloads`. This way my sonarr/radarr/plex containers can all access **both** my media folder and my download folder for file management.
> 
> image
> 
> By the way @jfroment, I think there may be a typo in [this line](https://github.com/jfroment/seedbox/blob/f42022744bac36da3a9bd27cc934b959270329f0/.env.sample#L24) of the sample env file, the download subfolder will be located in HOST_MEDIA_PATH and not in HOST_CONFIG_PATH (as seen [here](https://github.com/jfroment/seedbox/blob/f42022744bac36da3a9bd27cc934b959270329f0/docker-compose.sample.yaml#L23))

Nice reply, thx ! I integrate that and fix my PR about that.

**Comment by jfroment** [comment]
Yes @tblaudez you're perfectly right.

Media (what is called ``torrents`` by default here) directory has a subdirectory for downloads (named ``deluge`` by default).
This way with only a single mount for each *arr service for the media / library part, you have access to both downloads and definitive organized library, thus allowing you to do hardlinks to avoid wasting storage space.
(i.e your downloads (or deluge) directory can be messy and not organized at all, but your library is correctly organized following *arr services configuration).

To recap, by default the structure is the following:

```
data/
├─ torrents (or media if you prefer)/ <== This is $HOST_MEDIA_PATH
│  ├─ deluge (or downloads if you prefer)/ <== This is $DOWNLOAD_SUBFOLDER
│  ├─ Movies
│  ├─ TV Shows
│  ├─ Movies 4K
│  ├─ Documents <== This is $DOCUMENTS_SUBFOLDER
│  ├─ Books
│  ├─ [...]
├─ config/ <== This is $HOST_CONFIG_PATH
│  ├─ radarr/
│  ├─ sonarr/
│  ├─ other_services/
│  ├─ [...]
```

(see [here](https://wiki.servarr.com/en/docker-guide#examples) for more examples and explanations)

And of course everything is configurable using environment variables. But the idea to keep in mind is **to have both downloads (or deluge) directory and other libraries (movies, tv shows etc.) under the same common directory** to allow hardlinks for services like Sonarr/Radarr etc.

I agree with you, naming "torrents" and "deluge" the directories by default is far from ideal, but it is there for legacy purposes and if I change them I would introduce a breaking change, but I plan to do it quickly, the "media"/"downloads" default values are better indeed.

And you're right for the typo in the default .env.sample file, it should indicate HOST_MEDIA_PATH indeed. Thanks for the heads up.

**Pull request closed without merging**
